name: primeira-peline
on:
  push:
  - branches: ["main"] 
  workflow_dispatch:
jobs:
  primero_job:
    name: "Meu primeri Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World !!!"
      - name: "Segunda ação"
        run:
          echo "Voce criou o seu primeiro workflow !!!}"
          echo "Parabéns !!!"
          
        
