name: primeira-peline
on:
  push:
    branches: ["main"] 
  workflow_dispatch:
jobs:
  primero-job:
    name: "Meu primerio Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World !!!"
      - name: "Segunda ação"
        run: |
          echo "Voce criou o seu primeiro workflow !!!}"
          echo "Parabéns !!!"
      - name: "Script Python"
        run: |
          variavel = "Hello World !!!"
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalação do ambiente NodeJS"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificação da versão do NodeJS atual"
      - uses: actions/setup-node@v4.2.0
    with:
      node-version: '22.14.0'
      - name: "Verificação da versão do NodeJS atual depois de instalado"
        run: node --version
    
        
