name: primeira-peline
on:
  push:
    branches: ["main"] 
  workflow_dispatch:
jobs:
  primero-job:
    name: "Meu primerio Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World !!!"
      - name: "Segunda ação"
        run: |
          echo "Voce criou o seu primeiro workflow !!!}"
          echo "Parabéns !!!"
      - name: "Script Python"
        run: |
          variavel = "Hello World !!!"
          print(variavel)
        shell: python
        
